name: Benchmark (Main)

# Run on main branch after merge
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'benches/**'
      - 'tests/**'
      - 'benchflow.yaml'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Run Performance Benchmarks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup Rust (if needed)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        continue-on-error: true

      - name: Setup Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        continue-on-error: true

      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        continue-on-error: true

      - name: Run Performance Benchmarks
        uses: ./actions/benchmarkflow
        with:
          config: ./benchflow.yaml
          parallel: 4
          timeout: 10m
          format: html
          comment-pr: false
          detect-regression: true
          regression-threshold: '1.05'
          baseline-branch: main
          upload-artifact: true

      - name: Upload to Performance Tracking
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-reports-${{ github.run_id }}
          path: reports/
          retention-days: 90

      - name: Notify on Regression
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Performance Regression Detected',
              body: `A performance regression was detected in the latest commit.\n\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\nPlease review and address the regression.`,
              labels: ['performance', 'regression']
            });
